---

- name: install nsupdate which is used by the certbot auth-hook
  apt:
    pkg: dnsutils
    state: present
  when: letsencrypt_cert is defined and letsencrypt_cert.challenge|default() == 'dns'

- name: install Let's Encrypt Certbot client
  apt:
    pkg: certbot
    state: present

- name: install certbot plugin 'apache' on webservers
  apt:
    pkg: python3-certbot-apache
    state: present
  when: ansible_fqdn in groups[letsencrypt_webserver_groupname]|d([])
