---
- name: install packages
  include_tasks: "{{ ansible_os_family }}.yml"

- block:
    - name: install certbot DNS challenge helper script
      template:
        src: certbot-dns-hook.sh.j2
        dest: /usr/local/bin/certbot-dns-hook.sh
        owner: root
        group: root
        mode: 0755
    - name: create directory /etc/letsencrypt/keys
      file:
        dest: /etc/letsencrypt/keys
        state: directory
        owner: root
        group: root
        mode: 0700
    - name: install certbot DNS challenge nsupdate key
      copy:
        content: "{{ letsencrypt_ddns_key }}"
        dest: /etc/letsencrypt/keys/ddns_update.key
        owner: root
        group: root
        mode: 0400
      when: letsencrypt_ddns_key|default()
    - name: install certbot DNS challenge nsupdate private key
      copy:
        content: "{{ letsencrypt_ddns_privkey }}"
        dest: /etc/letsencrypt/keys/ddns_update.private
        owner: root
        group: root
        mode: 0400
      when: letsencrypt_ddns_privkey|default()
  when: letsencrypt_dns_challenge

- block:
    - name: add system group 'letsencrypt'
      group:
        name: letsencrypt
        system: true
    - name: adjust permissions for certificate directories
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: letsencrypt
        mode: 0750
      with_items:
        - /etc/letsencrypt/archive
        - /etc/letsencrypt/live
  when: letsencrypt_group

- name: check if letsencrypt_account_email is set
  fail:
    msg: "Error: either set letsencrypt_account_email or add '--register-unsafely-without-email' to letsencrypt_opts_extra"
  when:
    - not '--register-unsafely-without-email' in letsencrypt_opts_extra
    - not letsencrypt_account_email
  tags:
    - molecule-notest

- name: check if a Let's Encrypt account exists
  stat:
    path: /etc/letsencrypt/accounts
  register: letsencrypt_reg_accounts_dir

- name: prepare optional test cert option
  set_fact:
    letsencrypt_opt_email: "{{ letsencrypt_account_email|ternary('--email ' + letsencrypt_account_email,'') }}"

- name: prepare optional test cert option
  set_fact:
    letsencrypt_opt_test_cert: "{{ letsencrypt_test|default()|ternary('--test-cert','') }}"

- name: create Let's Encrypt account
  command: >
    certbot register
    {{ letsencrypt_opt_test_cert }}
    {{ letsencrypt_opt_email }}
    {{ letsencrypt_opts_extra }}
    --non-interactive --agree-tos --quiet
  when: not letsencrypt_reg_accounts_dir.stat.exists
  tags:
    - molecule-notest
